import Link from "next/link";
import {Catalog} from "@/components/Catalog";

const buyerSteps=[
  ["01","Descubre","Busca APIs HTTP y tools MCP por intención y filtros."],
  ["02","Inspecciona","Revisa precio declarado, asset, esquema, red y route template."],
  ["03","Paga con x402","Próximo milestone: exact sobre Stellar Testnet. No está activo hoy."],
  ["04","Recibe resultado","El servicio responde; Bazaar no custodia ni ejecuta la política del buyer."]
];
const providerSteps=[
  ["01","Publica una service card","Describe un servicio invocable, no un perfil humano o de agente."],
  ["02","Adjunta discovery metadata","Ruta, inputs, outputs y payment requirements validables."],
  ["03","Obtén el primer pago válido","Futuro Testnet: facilitador x402 externo, sin custodia del Bazaar."],
  ["04","Queda indexado","El índice offchain registra estado y outcomes de validación."]
];

export default function Home(){return <main>
  <div className="mock-banner">MVP LOCAL · SWAP RISK QUOTE ES READ-ONLY Y REAL · PAGOS x402 / STELLAR AÚN NO IMPLEMENTADOS</div>
  <nav className="nav shell"><Link href="/" className="brand"><span>✦</span> Stellar Bazaar <sup>x402</sup></Link><div className="nav-links"><a href="#producto">Qué es</a><a href="#catalogo">Catálogo</a><a href="#flujos">Flujos</a><Link href="/publish">Publica tu servicio</Link><a href="https://github.com/CaBsCrypto/stellar-bazaar-x402">GitHub ↗</a></div><span className="network-pill"><i/> Local MVP</span></nav>
  <header className="hero shell"><div className="hero-copy"><span className="kicker">DISCOVERY LAYER FOR PAID SERVICES ON STELLAR</span><h1>Encuentra el servicio.<br/><em>Entiende antes de pagar.</em></h1><p>Un catálogo Stellar-native de APIs HTTP y herramientas MCP pagadas. El MVP demuestra discovery y una llamada local real; x402 exact en Testnet es el siguiente paso.</p><div className="hero-actions"><Link className="primary" href="/resources/swap-risk-quote">Probar Swap Risk Quote →</Link><a className="ghost" href="#catalogo">Explorar catálogo</a></div><div className="trust-line"><span>Servicios, no perfiles</span><span>Metadata visible</span><span>Sin custodia ni firma</span></div></div><div className="orbital" aria-label="Flujo conceptual de discovery"><div className="orbit orbit-one"><span>HTTP</span></div><div className="orbit orbit-two"><span>MCP</span></div><div className="core"><small>DISCOVER</small><strong>✦</strong><span>x402 future</span></div><div className="floating quote">HOY<br/><b>LOCAL API ✓</b></div><div className="floating settle">DESPUÉS<br/><b>TESTNET x402</b></div></div></header>

  <section className="definition shell" id="producto"><div><span className="kicker">UNA FRONTERA CLARA</span><h2>Bazaar indexa servicios pagados.</h2><p>Ayuda a buyers y agentes a encontrar rutas invocables, comparar metadata relevante y llegar al proveedor correcto.</p><Link href="/resources/swap-risk-quote" className="text-link">Ver un recurso funcionando →</Link></div><div className="definition-grid"><article className="yes"><span>SÍ ES</span><strong>Discovery + catálogo</strong><p>Service cards, búsqueda, filtros, contratos de entrada/salida y requisitos de pago declarados.</p></article><article className="no"><span>NO ES</span><strong>Wallet ni marketplace de perfiles</strong><p>No custodia, no firma, no escrow, no Passport y no contrata personas o agentes.</p></article></div></section>

  <div className="shell"><Catalog/></div>

  <section className="journeys shell" id="flujos"><div className="section-heading"><div><span className="kicker">DOS CAMINOS, UN CATÁLOGO</span><h2>Cómo entra y sale valor.</h2></div><p>Los pasos futuros están marcados explícitamente.</p></div><div className="journey-grid"><div className="journey"><div className="journey-title"><span>BUYER / AGENT</span><h3>De intención a resultado</h3></div>{buyerSteps.map(([n,title,copy],i)=><article key={n} className={i===2?"future-step":""}><b>{n}</b><div><strong>{title}</strong><p>{copy}</p></div>{i===2&&<em>FUTURO TESTNET</em>}</article>)}</div><div className="journey provider"><div className="journey-title"><span>PROVIDER</span><h3>De servicio a índice</h3></div>{providerSteps.map(([n,title,copy],i)=><article key={n} className={i===2?"future-step":""}><b>{n}</b><div><strong>{title}</strong><p>{copy}</p></div>{i===2&&<em>FUTURO TESTNET</em>}</article>)}</div></div></section>

  <section className="boundaries"><div className="shell"><div className="boundary-head"><span className="kicker">TRUST & SAFETY</span><h2>Metadata para decidir.<br/>Control en manos del cliente.</h2><p>Bazaar hace visible el contrato del servicio, pero no reemplaza la política de seguridad del buyer.</p></div><div className="boundary-grid"><article><span>01</span><strong>No custodia fondos</strong><p>Los pagos futuros irán del buyer al flujo x402/facilitator; el índice no guarda balances.</p></article><article><span>02</span><strong>No firma autorizaciones</strong><p>La firma y consentimiento pertenecen al wallet o agente cliente, fuera del Bazaar.</p></article><article><span>03</span><strong>No impone buyer policy</strong><p>Cada cliente decide allowlists, límites, assets y aprobación humana.</p></article><article><span>04</span><strong>Expone señales</strong><p>Las cards muestran red, asset, esquema, precio, inputs, outputs y provenance para evaluar.</p></article></div></div></section>

  <section className="milestones shell" id="roadmap"><div className="section-heading"><div><span className="kicker">ESTADO HONESTO</span><h2>Hoy funciona una llamada. Mañana, el pago.</h2></div></div><div className="milestone-grid"><article className="current"><span>AHORA · MVP INSTAWARDS</span><h3>Discovery → endpoint local → resultado</h3><ul><li>Catálogo HTTP + MCP con fixtures</li><li>Swap Risk Quote determinista y read-only</li><li>Validación estructurada 200/400</li><li>Sin wallet, pago o chain write</li></ul><Link className="primary" href="/resources/swap-risk-quote">Ejecutar demo local</Link></article><article><span>SIGUIENTE · TESTNET</span><h3>x402 exact con facilitator existente</h3><ul><li>Integrar @x402/stellar, no reimplementar verify/settle</li><li>Autorización del lado del buyer</li><li>USDC default y evidencia reproducible</li><li>Conformance antes de claims</li></ul></article><article><span>DESPUÉS · HARDENING</span><h3>Discovery evaluado + self-hosting</h3><ul><li>Ingest validado y ranking medido</li><li>MCP discovery server</li><li>Facilitator propio sólo tras security review</li><li>Pubnet y uptime sólo tras auditoría</li></ul></article></div></section>
  <section className="final-cta shell"><span>ABIERTO A PROVIDERS Y BUYERS</span><h2>Prueba un servicio o diseña el tuyo.</h2><p>El provider conserva su precio, destino, términos y resultado. Bazaar ofrece discovery y conformance, no custodia.</p><div className="hero-actions" style={{justifyContent:"center"}}><Link className="primary" href="/resources/swap-risk-quote">Abrir Swap Risk Quote →</Link><Link className="ghost" href="/publish">Publica tu servicio</Link></div></section>
  <footer className="shell"><div className="brand"><span>✦</span> Stellar Bazaar x402</div><p>Apache-2.0 · Local Instawards MVP · ES first</p><p>Pagos Stellar: próximo milestone</p></footer>
</main>}
