"use client";
import { useState } from "react";
type ServiceId = "script-creator" | "video-repurpose";
type Payload = Record<string, unknown> & { executionRequest?: Record<string, unknown> };
const AUTH = "buyer-policy-approved-local-demo";
const services = { "script-creator": { es: "Creación de guion", en: "Script creation", mode: "sync" }, "video-repurpose": { es: "Edición de video", en: "Video repurpose", mode: "async" } };
export function BuyerExecutionDemo() {
  const [serviceId, setServiceId] = useState<ServiceId>("script-creator"); const [topic, setTopic] = useState("Explicar Stellar x402"); const [sourceName, setSourceName] = useState("demo-source.mp4"); const [phase, setPhase] = useState("input"); const [executionRequest, setExecutionRequest] = useState<Record<string, unknown> | null>(null); const [payload, setPayload] = useState<Payload | null>(null); const [busy, setBusy] = useState(false);
  const input = serviceId === "script-creator" ? { topic, durationSeconds: 60, tone: "educational" } : { sourceName, output: "vertical-short", targetSeconds: 45 };
  async function post(body: Record<string, unknown>) { const response = await fetch("/api/buyer-execution/reference", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); return { response, data: await response.json() as Payload }; }
  async function challenge() { setBusy(true); try { const { response, data } = await post({ action: "challenge", serviceId, input }); setPayload(data); if (response.status !== 402 || !data.executionRequest) throw new Error(); setExecutionRequest(data.executionRequest); setPhase("challenge"); } catch { setPayload({ error: { code: "LOCAL_DEMO_UNAVAILABLE" } }); setPhase("error"); } finally { setBusy(false); } }
  async function execute() { if (!executionRequest) return; setBusy(true); setPhase("execute"); try { const { response, data } = await post({ action: "execute", executionRequest, demoAuthorization: AUTH }); setPayload(data); setPhase(response.ok ? "delivered" : "error"); } catch { setPayload({ error: { code: "LOCAL_PROVIDER_UNAVAILABLE" } }); setPhase("error"); } finally { setBusy(false); } }
  async function poll() { if (!executionRequest) return; const envelope = payload?.envelope as { delivery?: { jobId?: string } } | undefined; setBusy(true); try { const { response, data } = await post({ action: "status", executionRequest, jobId: envelope?.delivery?.jobId }); setPayload(data); setPhase(response.ok ? "completed" : "error"); } catch { setPayload({ error: { code: "LOCAL_STATUS_UNAVAILABLE" } }); setPhase("error"); } finally { setBusy(false); } }
  function reset(next = serviceId) { setServiceId(next); setPhase("input"); setExecutionRequest(null); setPayload(null); }
  return <section className="buyer-execution" aria-labelledby="buyer-execution-title"><div className="buyer-execution__notice">FIXTURE LOCAL / LOCAL FIXTURE · 402 SIMULADO / SIMULATED · SIN WALLET / NO WALLET · SIN PAGO / NO PAYMENT · SIN UPLOAD / NO UPLOAD · SIN PROVEEDOR EXTERNO / NO EXTERNAL PROVIDER</div>
    <header className="buyer-execution__header"><div><span className="kicker">BUYER EXECUTION · CONTRACTS v1</span><h1 id="buyer-execution-title">Del brief a una entrega verificable.</h1><p lang="en">From buyer brief to a verifiable delivery.</p></div><div className="buyer-execution__scope"><strong>Estado / Current state</strong><span>Dos verticales locales y deterministas</span><span lang="en">Two local, deterministic verticals</span></div></header>
    <div className="buyer-execution__services" role="group" aria-label="Fixture service"><button aria-pressed={serviceId === "script-creator"} className={serviceId === "script-creator" ? "active" : ""} onClick={() => reset("script-creator")}><strong>{services["script-creator"].es}</strong><span lang="en">{services["script-creator"].en}</span><small>{services["script-creator"].mode}</small></button><button aria-pressed={serviceId === "video-repurpose"} className={serviceId === "video-repurpose" ? "active" : ""} onClick={() => reset("video-repurpose")}><strong>{services["video-repurpose"].es}</strong><span lang="en">{services["video-repurpose"].en}</span><small>{services["video-repurpose"].mode}</small></button></div>
    <ol className="buyer-execution__steps"><li className="active" aria-current={phase === "input" ? "step" : undefined}><b>01</b><span>Brief</span><small>Input</small></li><li className={phase !== "input" ? "active" : ""} aria-current={phase === "challenge" ? "step" : undefined}><b>02</b><span>Challenge local</span><small>Local challenge</small></li><li className={["execute","delivered","completed"].includes(phase) ? "active" : ""} aria-current={phase === "execute" ? "step" : undefined}><b>03</b><span>Autorizar</span><small>Authorize</small></li><li className={["delivered","completed"].includes(phase) ? "active" : ""} aria-current={phase === "delivered" && serviceId === "video-repurpose" ? "step" : undefined}><b>04</b><span>Entrega</span><small>Delivery</small></li><li className={phase === "completed" || (phase === "delivered" && serviceId === "script-creator") ? "active" : ""} aria-current={phase === "completed" || (phase === "delivered" && serviceId === "script-creator") ? "step" : undefined}><b>05</b><span>Reconciliar</span><small>Reconcile</small></li></ol>
    <div className="buyer-execution__grid"><form className="buyer-execution__form" onSubmit={(e) => e.preventDefault()}><h2>{services[serviceId].es}</h2><p lang="en">{services[serviceId].en}</p>{serviceId === "script-creator" ? <label>Tema / Topic<input value={topic} onChange={(e) => setTopic(e.target.value)} disabled={phase !== "input"}/></label> : <label>Nombre de archivo (metadata) / File name<input value={sourceName} onChange={(e) => setSourceName(e.target.value)} disabled={phase !== "input"}/></label>}<div className="buyer-execution__contract"><span>MODELO DE ENTREGA / DELIVERY MODEL</span><strong>{services[serviceId].mode}</strong><small>{serviceId === "script-creator" ? "Texto estructurado y hash canónico / Structured text and canonical hash." : "jobId, progreso y handoff ficticio / jobId, progress, and fixture handoff."}</small></div><div className="buyer-execution__actions"><button type="button" className="ghost" onClick={() => reset()}>Reiniciar / Reset</button>{phase === "input" && <button type="button" className="primary" onClick={challenge} disabled={busy}>Solicitar 402 local / Request local 402</button>}{phase === "challenge" && <button type="button" className="primary" onClick={execute} disabled={busy}>Autorizar y ejecutar fixture / Authorize & run fixture</button>}</div></form><section className="buyer-execution__output" aria-live="polite" aria-busy={busy}><div className="terminal-head"><span/><span/><span/><code>delivery-envelope-v1.json</code></div>{payload ? <pre>{JSON.stringify(payload, null, 2)}</pre> : <div className="buyer-execution__empty"><strong>Esperando brief / Waiting for brief</strong><p>Inspecciona cada transición antes de continuar.</p><p lang="en">Inspect every transition before continuing.</p></div>}</section></div>
    {phase === "delivered" && serviceId === "video-repurpose" && <div className="buyer-execution__actions"><button type="button" className="primary" onClick={poll} disabled={busy}>Consultar estado y completar fixture / Poll status and complete fixture</button></div>}
    {["delivered","completed"].includes(phase) && <div className="buyer-execution__delivered"><article><span>ENTREGA / DELIVERY</span><strong>{serviceId === "script-creator" ? "Guion estructurado listo / Structured script ready" : phase === "completed" ? "Artefacto fixture completado / Fixture artifact completed" : "Job asíncrono en proceso / Async job processing"}</strong><p>{serviceId === "script-creator" ? "Contenido y hash canónico / Content and canonical hash." : "Job ID, estado y manifest verificable; ningún archivo real fue subido / Verifiable status and manifest; no real file was uploaded."}</p></article><article><span>RECONCILIACIÓN / RECONCILIATION</span><strong>Bindings v1 coinciden / v1 bindings match</strong><p>Request, ruta, input, idempotencia y resultado están vinculados; sin pago / Request, route, input, idempotency and result are bound; no payment.</p></article></div>}
    <aside className="buyer-execution__boundary"><strong>Bazaar muestra la entrega; no firma, no custodia, no aloja archivos y no certifica calidad.</strong><strong lang="en">Bazaar displays delivery; it does not sign, hold funds, host files, or certify quality.</strong><p>Este workspace prueba contratos y estados locales. No existe settlement, escrow, storage ni ejecución externa.</p><p lang="en">This workspace tests local contracts and states. There is no settlement, escrow, storage, or external execution.</p></aside></section>;
}
