"use client";
import {useState} from "react";
import type {PaidService} from "@/lib/types";
const labels=["Descubierto","Configurar","Llamar endpoint","Resultado"];
export function PaymentDemo({service}:{service:PaidService}){
 const [step,setStep]=useState(0),[amount,setAmount]=useState("2500"),[side,setSide]=useState("buy"),[loading,setLoading]=useState(false);
 const initial={resourceId:service.id,discovered:true,source:"static_catalogue"}; const [payload,setPayload]=useState<object>(initial);
 async function advance(){if(step===0){setStep(1);setPayload({pair:"XLM/USDC",amount:Number(amount),side,ready:true});return}if(step===1){setLoading(true);setStep(2);try{const response=await fetch(`/api/reference/swap-risk?pair=XLM%2FUSDC&amount=${encodeURIComponent(amount)}&side=${side}`);setPayload(await response.json() as object)}catch{setPayload({ok:false,error:{code:"LOCAL_ENDPOINT_UNAVAILABLE",retryable:true,stage:"call"}})}finally{setLoading(false);setStep(3)}}}
 return <section className="demo-panel"><div className="mock-ribbon">DEMO LOCAL · REFERENCIA GRATUITA /api/reference/swap-risk · EL FLUJO PAGADO x402 EN VIVO ESTÁ EN /api/x402/swap-risk</div><div className="stepper">{labels.map((label,index)=><div className={index<=step?"step reached":"step"} key={label}><span>{index<step?"✓":index+1}</span><small>{label}</small></div>)}</div><div className="reference-note"><strong>Referencia gratuita (demo local, in-process).</strong> Se extraerá como servicio separado. El flujo pagado x402 exact en Stellar Testnet está en vivo: GET /api/x402/swap-risk (402 → pago → 200 con PAYMENT-RESPONSE), 0.001 USDC.</div>{step===1&&<div className="quote-form"><label>Monto nocional<input type="number" min="1" max="1000000" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Lado<select value={side} onChange={e=>setSide(e.target.value)}><option value="buy">Comprar</option><option value="sell">Vender</option></select></label></div>}<div className="terminal-card"><div className="terminal-head"><span/><span/><span/><code>local-response.json</code></div><pre>{loading?"Llamando GET /api/reference/swap-risk …":JSON.stringify(payload,null,2)}</pre></div><div className="demo-actions"><button className="ghost" onClick={()=>{setStep(0);setPayload(initial)}} disabled={step===0}>Reiniciar</button><button className="primary" onClick={advance} disabled={step===labels.length-1||loading}>{step===0?"Configurar consulta":"Llamar proveedor local"}</button></div></section>
}
