import { toPromiseSummary } from "@/lib/promise-summary";
import type { ServicePromise } from "@/lib/service-order";

const website: ServicePromise = { deliveryMode: "sync", estimatedDurationMs: 30_000, outputKinds: ["audit", "findings", "score"], resultSchemaVersion: "1.0", retentionHours: 0, revision: { includedRevisions: 0, revisionWindowHours: 0, responseSlaHours: 24, scopeChangePolicy: "new-brief-required", refundPolicy: "provider-declared" } };
const video: ServicePromise = { deliveryMode: "async", estimatedDurationMs: 7_200_000, outputKinds: ["job", "clips", "captions"], resultSchemaVersion: "1.0", retentionHours: 72, revision: { includedRevisions: 1, revisionWindowHours: 48, responseSlaHours: 24, scopeChangePolicy: "provider-quote-required", refundPolicy: "provider-declared" } };
const brand: ServicePromise = { deliveryMode: "async", estimatedDurationMs: 172_800_000, outputKinds: ["strategy", "logo", "cover"], resultSchemaVersion: "1.0", retentionHours: 168, revision: { includedRevisions: 2, revisionWindowHours: 168, responseSlaHours: 48, scopeChangePolicy: "new-brief-required", refundPolicy: "provider-declared" } };
const promises = [toPromiseSummary("website-intelligence-pilot", { es: "Website Intelligence", en: "Website Intelligence" }, website), toPromiseSummary("video-repurpose-pilot", { es: "Video Repurpose", en: "Video Repurpose" }, video), toPromiseSummary("brand-identity-studio-pilot", { es: "Brand Identity Studio", en: "Brand Identity Studio" }, brand)];

export function PromiseSummarySection() {
  return <section className="promise-section shell" id="promesa"><div className="section-heading"><div><span className="kicker">PROMESA DEL SERVICIO</span><h2>Antes de pagar, el buyer recibe un brief y una promesa clara.</h2></div><p>Valores declarados por el provider; los pilotos no aceptan pago.</p></div><div className="promise-grid">{promises.map((item) => <article key={item.serviceId}><span>PILOT · PROVIDER-REPORTED</span><h3>{item.label.es}</h3><p>{item.delivery.es}</p><dl><div><dt>Entregables</dt><dd>{item.outputs.join(" · ")}</dd></div><div><dt>Revisiones</dt><dd>{item.revisions.included} incluidas · ventana {item.revisions.windowHours}h</dd></div><div><dt>Retención</dt><dd>{item.retentionHours}h</dd></div></dl><small>Un brief define objetivo, insumos y criterios de éxito. Bazaar no certifica la calidad.</small></article>)}</div></section>;
}
