import{McpServer}from"@modelcontextprotocol/sdk/server/mcp.js";import*as z from"zod/v4";import{services}from"./catalog";import{rankServices,validateServiceCard}from"./discovery";import{toServiceCard}from"./service-card";import{getExternalQuoteCard}from"./external-provider";
const json=(value:unknown)=>({content:[{type:"text" as const,text:JSON.stringify(value)}],structuredContent:value as Record<string,unknown>});
export function createDiscoveryMcpServer(){const server=new McpServer({name:"stellar-bazaar-discovery",version:"0.1.0"});
 server.registerTool("get_bazaar_capabilities",{description:"Read-only Bazaar capability card. No signing or payment.",inputSchema:{}},async()=>json({version:"bazaar.mcp-capabilities/v1",transport:"streamable-http",mode:"read-only",tools:["get_bazaar_capabilities","list_services","search_services","get_service","validate_service_card"],paidCall:false,signing:false,custody:false}));
 server.registerTool("list_services",{description:"List local service cards plus the truthful external Quote contract.",inputSchema:{}},async()=>json({results:[...services.map(toServiceCard),getExternalQuoteCard()],partialResults:false}));
 server.registerTool("search_services",{description:"Deterministic lexical search; no AI or safety inference.",inputSchema:{query:z.string().min(1)}},async({query})=>json({query,ranking:{version:"lexical-v1",ai:false},results:rankServices(services,query).map(x=>({resource:toServiceCard(x.service),score:x.score,reasons:x.reasons})),partialResults:false}));
 server.registerTool("get_service",{description:"Get one service by machine-stable ID.",inputSchema:{id:z.string().min(1)}},async({id})=>{if(id==="stellar-defi-quote-service")return json({resource:getExternalQuoteCard()});const service=services.find(x=>x.id===id);if(!service)return{isError:true,content:[{type:"text" as const,text:JSON.stringify({code:"RESOURCE_NOT_FOUND",message:"Unknown service id",retryable:false,stage:"discover"})}]};return json({resource:toServiceCard(service)})});
 server.registerTool("validate_service_card",{description:"Shape conformance only; never provider certification.",inputSchema:{card:z.record(z.string(),z.unknown())}},async({card})=>{try{const outcomes=validateServiceCard(card as never);return json({valid:!outcomes.some(x=>x.status==="fail"),outcomes,certification:false})}catch{return json({valid:false,outcomes:[{rule:"schema.shape",status:"fail",reason:"Malformed service card"}],certification:false})}});
 return server}
