/** Buyer-owned order semantics. Payment and escrow are deliberately separate. */
export const SERVICE_ORDER_VERSION = "bazaar.service-order/v1" as const;
export type OrderStatus = "draft" | "accepted" | "processing" | "delivered" | "revision-requested" | "accepted-by-buyer" | "failed" | "cancelled" | "expired";
export interface BuyerBrief { version: typeof SERVICE_ORDER_VERSION; serviceId: string; objective: string; inputs: Record<string, string | number | boolean | string[]>; successCriteria: string[]; constraints?: string[]; requestedDeadline?: string; locale: "es" | "en"; dataConsent: "provider-terms-accepted" | "not-provided"; idempotencyKey: string; }
export interface RevisionPolicy { includedRevisions: number; revisionWindowHours: number; responseSlaHours: number; scopeChangePolicy: "new-brief-required" | "provider-quote-required"; refundPolicy: "provider-declared" | "not-offered"; }
export interface ServicePromise { deliveryMode: "sync" | "async"; estimatedDurationMs: number; outputKinds: string[]; resultSchemaVersion: string; retentionHours: number; revision: RevisionPolicy; }
export type TransitionResult = { ok: true; status: OrderStatus } | { ok: false; code: "INVALID_TRANSITION" };
const transitions: Record<OrderStatus, OrderStatus[]> = { draft: ["accepted", "cancelled", "expired"], accepted: ["processing", "failed", "cancelled", "expired"], processing: ["delivered", "failed", "expired"], delivered: ["accepted-by-buyer", "revision-requested", "expired"], "revision-requested": ["processing", "failed", "expired"], "accepted-by-buyer": [], failed: [], cancelled: [], expired: [] };
export function transitionOrder(from: OrderStatus, to: OrderStatus): TransitionResult { return transitions[from].includes(to) ? { ok: true, status: to } : { ok: false, code: "INVALID_TRANSITION" }; }
export function validateBuyerBrief(brief: BuyerBrief): string[] { const errors: string[] = []; if (brief.version !== SERVICE_ORDER_VERSION) errors.push("brief.version"); if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(brief.serviceId)) errors.push("brief.serviceId"); if (!brief.objective.trim()) errors.push("brief.objective"); if (!brief.idempotencyKey.trim()) errors.push("brief.idempotencyKey"); if (!brief.successCriteria.length || brief.successCriteria.some((item) => !item.trim())) errors.push("brief.successCriteria"); if (brief.dataConsent !== "provider-terms-accepted") errors.push("brief.dataConsent"); return errors; }
export function validateServicePromise(promise: ServicePromise): string[] { const errors: string[] = []; if (promise.estimatedDurationMs <= 0) errors.push("promise.estimatedDurationMs"); if (!promise.outputKinds.length) errors.push("promise.outputKinds"); if (!promise.resultSchemaVersion.trim()) errors.push("promise.resultSchemaVersion"); if (promise.retentionHours < 0) errors.push("promise.retentionHours"); if (!Number.isInteger(promise.revision.includedRevisions) || promise.revision.includedRevisions < 0) errors.push("promise.revision.includedRevisions"); if (promise.revision.revisionWindowHours < 0 || promise.revision.responseSlaHours <= 0) errors.push("promise.revision.timing"); return errors; }
